MERGE_DICT = {
    "Python": ["Python / Django", "Python3",
               "Python/Django/Django-rest-framework", "Django/Python",
               "Python basics", "Python scripting", "Python3+", "python"],
    "Django": ["Python / Django", "Python/Django/Django-rest-framework",
               "Django/Flask/Aiohttp/FastApi", "Django/Python"],
    "Django REST Framework": ["Python/Django/Django-rest-framework",
                              "Django Rest Framework", "Django REST"],
    "Machine Learning": ["ML"],
    "AI": ["AI technology"],
    "SQL": ["SQL or DWH", "SQL/NoSQL"],
    "MySQL": ["MySQL/PostgreSQL/MongoDB", "MongoDB/PostgreSQL/MySQL",
              "MySQL/PostgreSQL", "MySQL/Postgres"],
    "Postgres": ["MySQL/PostgreSQL/MongoDB", "PostgreSQL",
                 "MongoDB/PostgreSQL/MySQL", "MySQL/PostgreSQL",
                 "MySQL/Postgres", "Postgre SQL"],
    "MongoDB": ["MySQL/PostgreSQL/MongoDB", "Mongo DB",
                "MongoDB/PostgreSQL/MySQL"],
    "SQLAlchemy": ["SQLAlchemy and Alembic"],
    "FastAPI": ["FastApi", "Django/Flask/Aiohttp/FastApi", "Fast API",
                "AIOHTTP / Starlette / FastAPI", "Flask / FastAPI / asyncio"],
    "AWS": ["AWS Lambda", "AWS / EC2 / ECS / EKS", "AWS / GCP / Azure",
            "AWS S3", "AWS S3/RDS/EC2/Fargate/Lambda/S3", "AWS SQS",
            "AWS/GCP/Azure"],
    "Azure DevOps": ["AWS / GCP / Azure", "AWS/GCP/Azure", "Azure Cloud",
                     "Azure OpenAI", "Microsoft Azure"],
    "Flask": ["Django/Flask/Aiohttp/FastApi", "Flask / FastAPI / asyncio"],
    "asyncio": ["Flask / FastAPI / asyncio"],
    "aiohttp": ["Django/Flask/Aiohttp/FastApi",
                "AIOHTTP / Starlette / FastAPI"],
    "Backend development": ["Backend", "back-end"],
    "BeautifulSoup": ["Beautifulsoup", "beautifulsoup"],
    "C": ["C/C++"],
    "C++": ["C/C++"],
    "CI/CD": ["CI / CD"],
    "Celery": ["Celery/RabbitMQ/Redis"],
    "RabbitMQ": ["Celery/RabbitMQ/Redis"],
    "Redis": ["Celery/RabbitMQ/Redis"],
    "Docker": ["Docker / Docker Compose", "Docker/Kubernetes"],
    "Docker Compose": ["Docker / Docker Compose"],
    "Kubernetes": ["Docker/Kubernetes", "K8s"],
    "Node.js": ["Node", "Node.js/Express.js/NestJS",
                "NodeJS/NestJS/Javascript/Typescript"],
    "JavaScript": ["NodeJS/NestJS/Javascript/Typescript", "JS", "React + JS"],
    "React": ["React + JS", "React.js", "React/Redux/Next.js"],
    "OpenAI": ["OpenAI APIs"],
    "REST API": ["REST", "REST/gRPC/Websockets/MQ"],
    "Salesforce": ["Salesforce CRM"],
}
